import { Account } from '../types';

/**
 * Standard Medical Chart of Accounts Generator
 * Generates an exhaustive, medically tailored Chart of Accounts for any clinic, center, or hospital.
 */
export function generateDefaultChartOfAccounts(clinicId: string, templateType: 'clinic' | 'center' | 'hospital' | 'pharmacy' = 'hospital'): Account[] {
  const timestamp = new Date().toISOString();
  
  const baseAccounts: Account[] = [
    // ================= 1. الأصول (Assets) =================
    {
      id: `${clinicId}_1`,
      clinicId,
      code: '1',
      name: 'الأصول',
      nameEn: 'Assets',
      type: 'asset',
      category: 'root',
      level: 1,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    // 11. الأصول المتداولة
    {
      id: `${clinicId}_11`,
      clinicId,
      code: '11',
      name: 'الأصول المتداولة',
      nameEn: 'Current Assets',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_1`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1101`,
      clinicId,
      code: '1101',
      name: 'الخزينة الرئيسية (النقدية بالصندوق)',
      nameEn: 'Main Cash / Safe',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'حساب النقدية بالخزينة الرئيسية للمنشأة',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1102`,
      clinicId,
      code: '1102',
      name: 'خزينة الاستقبال وعيادات الكشف',
      nameEn: 'Reception Cash Drawer',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'نقدية الاستقبال والتحصيل اليومي',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1103`,
      clinicId,
      code: '1103',
      name: 'الحسابات البنكية ونقاط البيع (POS)',
      nameEn: 'Bank Accounts & POS',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'المدفوعات الإلكترونية والحسابات الجارية',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1104`,
      clinicId,
      code: '1104',
      name: 'حسابات المرضى والعملاء (المدينون)',
      nameEn: 'Accounts Receivable (Patients)',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'مستحقات على المرضى والمراجعين',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1105`,
      clinicId,
      code: '1105',
      name: 'مدينو شركات التأمين الطبي والجهات المتعاقدة',
      nameEn: 'Insurance Companies Receivables',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'مطالبات التأمين الطبي قيد التحصيل',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1106`,
      clinicId,
      code: '1106',
      name: 'مخزون الصيدلية والأدوية',
      nameEn: 'Pharmacy Inventory',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'قيمة مخزون الأدوية والمستحضرات',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1107`,
      clinicId,
      code: '1107',
      name: 'مخزون المستلزمات الطبية والعمليات',
      nameEn: 'Medical Supplies & OR Inventory',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      description: 'مخزون الخيوط والشاش والفلاتر والمستهلكات',
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1108`,
      clinicId,
      code: '1108',
      name: 'سلف وعهد الموظفين والأطباء',
      nameEn: 'Staff Advances & Custodies',
      type: 'asset',
      category: 'current_assets',
      parentId: `${clinicId}_11`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // 12. الأصول الثابتة
    {
      id: `${clinicId}_12`,
      clinicId,
      code: '12',
      name: 'الأصول غير المتداولة (الثابتة)',
      nameEn: 'Fixed Assets',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_1`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1201`,
      clinicId,
      code: '1201',
      name: 'الأجهزة والمعدات الطبية وجراحة المناظير',
      nameEn: 'Medical Equipment & Endoscopes',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_12`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1202`,
      clinicId,
      code: '1202',
      name: 'أجهزة السونار والأشعة والتحاليل',
      nameEn: 'Ultrasound, Rad & Lab Devices',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_12`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1203`,
      clinicId,
      code: '1203',
      name: 'أثاث وتجهيزات العيادات وغرف المرضى',
      nameEn: 'Furniture & Fixtures',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_12`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1204`,
      clinicId,
      code: '1204',
      name: 'أجهزة الكمبيوتر والشبكات وشاشات الانتظار',
      nameEn: 'IT, Computers & TV Screens',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_12`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_1205`,
      clinicId,
      code: '1205',
      name: 'مجمع إهلاك الأصول الثابتة (دائن)',
      nameEn: 'Accumulated Depreciation',
      type: 'asset',
      category: 'fixed_assets',
      parentId: `${clinicId}_12`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // ================= 2. الخصوم والالتزامات (Liabilities) =================
    {
      id: `${clinicId}_2`,
      clinicId,
      code: '2',
      name: 'الخصوم والالتزامات',
      nameEn: 'Liabilities',
      type: 'liability',
      category: 'root',
      level: 1,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_21`,
      clinicId,
      code: '21',
      name: 'الخصوم المتداولة',
      nameEn: 'Current Liabilities',
      type: 'liability',
      category: 'current_liabilities',
      parentId: `${clinicId}_2`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_2101`,
      clinicId,
      code: '2101',
      name: 'موردو الأدوية والشركات الطبية (الدائنون)',
      nameEn: 'Accounts Payable (Suppliers)',
      type: 'liability',
      category: 'current_liabilities',
      parentId: `${clinicId}_21`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_2102`,
      clinicId,
      code: '2102',
      name: 'أتعاب ونسب أطباء مستحقة الدفع',
      nameEn: 'Accrued Doctors Fees',
      type: 'liability',
      category: 'current_liabilities',
      parentId: `${clinicId}_21`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_2103`,
      clinicId,
      code: '2103',
      name: 'رواتب وأجور موظفين وتمريض مستحقة',
      nameEn: 'Accrued Salaries & Wages',
      type: 'liability',
      category: 'current_liabilities',
      parentId: `${clinicId}_21`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_2104`,
      clinicId,
      code: '2104',
      name: 'مصلحة الضرائب (ضريبة القيمة المضافة VAT)',
      nameEn: 'VAT & Tax Payable',
      type: 'liability',
      category: 'current_liabilities',
      parentId: `${clinicId}_21`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_22`,
      clinicId,
      code: '22',
      name: 'الخصوم طويلة الأجل',
      nameEn: 'Long-term Liabilities',
      type: 'liability',
      category: 'long_term_liabilities',
      parentId: `${clinicId}_2`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_2201`,
      clinicId,
      code: '2201',
      name: 'قروض وتسهيلات بنكية وتمويل طبي',
      nameEn: 'Bank Loans & Medical Financing',
      type: 'liability',
      category: 'long_term_liabilities',
      parentId: `${clinicId}_22`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // ================= 3. حقوق الملكية (Equity) =================
    {
      id: `${clinicId}_3`,
      clinicId,
      code: '3',
      name: 'حقوق الملكية',
      nameEn: 'Equity',
      type: 'equity',
      category: 'root',
      level: 1,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_3101`,
      clinicId,
      code: '3101',
      name: 'رأس مال المنشأة / العيادة',
      nameEn: 'Paid-in Capital',
      type: 'equity',
      category: 'capital',
      parentId: `${clinicId}_3`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_3102`,
      clinicId,
      code: '3102',
      name: 'الأرباح والخسائر المرحلة (المبقاة)',
      nameEn: 'Retained Earnings',
      type: 'equity',
      category: 'retained_earnings',
      parentId: `${clinicId}_3`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_3103`,
      clinicId,
      code: '3103',
      name: 'جاري الشركاء / صاحب المنشأة',
      nameEn: 'Partners / Owner Current Account',
      type: 'equity',
      category: 'drawings',
      parentId: `${clinicId}_3`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_3104`,
      clinicId,
      code: '3104',
      name: 'أرباح العام الحالي',
      nameEn: 'Current Year Net Profit',
      type: 'equity',
      category: 'retained_earnings',
      parentId: `${clinicId}_3`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // ================= 4. الإيرادات (Revenues) =================
    {
      id: `${clinicId}_4`,
      clinicId,
      code: '4',
      name: 'الإيرادات',
      nameEn: 'Revenues',
      type: 'revenue',
      category: 'root',
      level: 1,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_41`,
      clinicId,
      code: '41',
      name: 'الإيرادات التشغيلية الطبية',
      nameEn: 'Operating Medical Revenues',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_4`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4101`,
      clinicId,
      code: '4101',
      name: 'إيرادات الكشوفات والاستشارات الطبية',
      nameEn: 'Consultation & Clinic Visit Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4102`,
      clinicId,
      code: '4102',
      name: 'إيرادات العمليات الجراحية والمناظير',
      nameEn: 'Surgical & Endoscopy Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4103`,
      clinicId,
      code: '4103',
      name: 'إيرادات الطوارئ والترياج والعناية المركزة',
      nameEn: 'ER, Triage & ICU Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4104`,
      clinicId,
      code: '4104',
      name: 'إيرادات الإقامة والتنويم والأجنحة',
      nameEn: 'Inpatient & Room Admission Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4105`,
      clinicId,
      code: '4105',
      name: 'إيرادات مبيعات الصيدلية والمستحضرات',
      nameEn: 'Pharmacy Sales Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4106`,
      clinicId,
      code: '4106',
      name: 'إيرادات الفحوصات والتحاليل المخبرية',
      nameEn: 'Laboratory Testing Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4107`,
      clinicId,
      code: '4107',
      name: 'إيرادات وحدة الأشعة والسونار',
      nameEn: 'Radiology & Imaging Revenue',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_4108`,
      clinicId,
      code: '4108',
      name: 'إيرادات الخدمات التمريضية والغيار والعلاج الطبيعي',
      nameEn: 'Nursing, Dressing & Physiotherapy',
      type: 'revenue',
      category: 'operating_revenue',
      parentId: `${clinicId}_41`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // ================= 5. المصروفات (Expenses) =================
    {
      id: `${clinicId}_5`,
      clinicId,
      code: '5',
      name: 'المصروفات والتكاليف',
      nameEn: 'Expenses & Costs',
      type: 'expense',
      category: 'root',
      level: 1,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_51`,
      clinicId,
      code: '51',
      name: 'تكاليف ومصروفات التشغيل الطبية',
      nameEn: 'Direct Medical Operating Costs',
      type: 'expense',
      category: 'operating_expenses',
      parentId: `${clinicId}_5`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5101`,
      clinicId,
      code: '5101',
      name: 'أتعاب ونسب الأطباء والاستشاريين',
      nameEn: 'Doctors & Consultants Share/Fees',
      type: 'expense',
      category: 'operating_expenses',
      parentId: `${clinicId}_51`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5102`,
      clinicId,
      code: '5102',
      name: 'تكلفة الأدوية والمستلزمات المباعة (COGS)',
      nameEn: 'Cost of Drugs & Medical Sold',
      type: 'expense',
      category: 'operating_expenses',
      parentId: `${clinicId}_51`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5103`,
      clinicId,
      code: '5103',
      name: 'مستهلكات العمليات والتخدير والتعقيم',
      nameEn: 'OR Supplies, Anesthesia & Sterilization',
      type: 'expense',
      category: 'operating_expenses',
      parentId: `${clinicId}_51`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5104`,
      clinicId,
      code: '5104',
      name: 'كيماويات ومستهلكات المعمل والأشعة',
      nameEn: 'Lab Reagents & Rad Consumables',
      type: 'expense',
      category: 'operating_expenses',
      parentId: `${clinicId}_51`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },

    // 52. المصروفات الإدارية والعمومية
    {
      id: `${clinicId}_52`,
      clinicId,
      code: '52',
      name: 'المصروفات الإدارية والعمومية',
      nameEn: 'General & Administrative Expenses',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_5`,
      level: 2,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5201`,
      clinicId,
      code: '5201',
      name: 'رواتب وأجور الكوادر والتمريض والإدارة',
      nameEn: 'Staff, Nursing & Admin Payroll',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5202`,
      clinicId,
      code: '5202',
      name: 'إيجار المقر والمنشأة الطبية',
      nameEn: 'Facility Rent Expense',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5203`,
      clinicId,
      code: '5203',
      name: 'المرافق (كهرباء، مياه، غاز، تكييف)',
      nameEn: 'Utilities (Electricity, Water, Gas)',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5204`,
      clinicId,
      code: '5204',
      name: 'الصيانة الدورية وقطع غيار الأجهزة',
      nameEn: 'Maintenance & Device Spare Parts',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5205`,
      clinicId,
      code: '5205',
      name: 'التسويق الطبي والدعاية والإعلان',
      nameEn: 'Marketing & Medical Advertising',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5206`,
      clinicId,
      code: '5206',
      name: 'اشتراكات البرمجيات والإنترنت والاتصالات',
      nameEn: 'Software, Internet & Telecom',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5207`,
      clinicId,
      code: '5207',
      name: 'إهلاك الأصول والمعدات الطبية',
      nameEn: 'Depreciation Expense',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5208`,
      clinicId,
      code: '5208',
      name: 'مصروفات بنكية ورسوم نقاط الدفع (POS)',
      nameEn: 'Bank Charges & POS Fees',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    },
    {
      id: `${clinicId}_5209`,
      clinicId,
      code: '5209',
      name: 'نثريات وضيافة ومطبوعات مكتبية',
      nameEn: 'Hospitality, Stationery & Miscellaneous',
      type: 'expense',
      category: 'admin_expenses',
      parentId: `${clinicId}_52`,
      level: 3,
      openingBalance: 0,
      currentBalance: 0,
      isSystemAccount: true,
      createdAt: timestamp
    }
  ];

  // Template-specific account injections
  if (templateType === 'hospital') {
    const hospitalAccounts: Account[] = [
      {
        id: `${clinicId}_1110`,
        clinicId,
        code: '1110',
        name: 'عهدة صيدلية الطوارئ والعمليات',
        nameEn: 'ER & OR Pharmacy Stock',
        type: 'asset',
        category: 'current_assets',
        parentId: `${clinicId}_11`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'عهدة الأدوية والسرنجات والمستلزمات في قسم الطوارئ والعمليات الكبرى',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_4110`,
        clinicId,
        code: '4110',
        name: 'إيرادات غرف العمليات الجراحية الكبرى (OR)',
        nameEn: 'Major Surgeries & OR Revenue',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'إيرادات غرف العمليات والمناظير الجراحية وتجهيزات غرف التخدير والعمليات الكبرى والوسطى',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_4111`,
        clinicId,
        code: '4111',
        name: 'إيرادات غرف العناية المركزة (ICU Admissions)',
        nameEn: 'ICU Admissions & Care Revenue',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'إيرادات الإقامة والتنفس الصناعي والمراقبة المستمرة في العناية المركزة وحضانات الأطفال',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_4112`,
        clinicId,
        code: '4112',
        name: 'إيرادات خدمات الطوارئ والإسعاف وعيادة الحوادث (ER)',
        nameEn: 'ER & Accident Trauma Clinic Revenue',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'إيرادات الإسعاف والفرز الأولي وخياطة الجروح والجبائر بقسم الطوارئ السريع',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5110`,
        clinicId,
        code: '5110',
        name: 'مصروفات إعاشة وتنويم وإطعام المرضى بالأجنحة',
        nameEn: 'Inpatient Catering & Ward Service Costs',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'تكلفة الوجبات، مغاسل الأغطية، النظافة، والتجهيزات المعيشية داخل أجنحة تنويم المرضى ومرافقيهم',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5111`,
        clinicId,
        code: '5111',
        name: 'تكلفة غازات طبية وأكسجين ومستلزمات تخدير العمليات',
        nameEn: 'Medical Gases, Oxygen & Anesthesia Costs',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'تكاليف غاز الأوكسجين المسال، أسطوانات النيتروز، فلاتر التنفس ومستهلكات غرف الجراحة والمناظير',
        createdAt: timestamp
      }
    ];
    return [...baseAccounts, ...hospitalAccounts];
  }

  if (templateType === 'center') {
    const centerAccounts: Account[] = [
      {
        id: `${clinicId}_4120`,
        clinicId,
        code: '4120',
        name: 'إيرادات عيادات الأسنان والتركيبات والزراعة',
        nameEn: 'Dental & Implantology Clinic Revenue',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'إيرادات الحشوات، التقويم، سحب العصب والتركيبات السنية التجميلية والعلاجية',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_4121`,
        clinicId,
        code: '4121',
        name: 'إيرادات جلسات العلاج الطبيعي والتأهيل الطبي',
        nameEn: 'Physiotherapy & Rehabilitation Sessions Revenue',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'إيرادات جلسات الموجات الصوتية والعلاج الحركي والمساج الطبي وتأهيل ما بعد الجراحات',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5120`,
        clinicId,
        code: '5120',
        name: 'مصاريف تسويق وعروض الباقات الطبية والإعلانات',
        nameEn: 'Marketing & Specialized Medical Campaigns Cost',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'تكاليف الحملات التسويقية الممولة للمركز الطبي، عروض اليوم الوطني وعروض العائلات والشركات',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5121`,
        clinicId,
        code: '5121',
        name: 'أتعاب تشغيل الأطباء المتعاقدين والزائرين ونسبهم',
        nameEn: 'Contractual & Visiting Consultants Shares',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'أتعاب الاستشاريين القادمين بموجب عقود زيارة مؤقتة أو نسب مئوية خاصة من الفحوصات المتطورة',
        createdAt: timestamp
      }
    ];
    return [...baseAccounts, ...centerAccounts];
  }

  if (templateType === 'clinic') {
    // For single clinics, keep it compact and filter out heavy hospital infrastructure accounts to simplify layout
    const filteredBase = baseAccounts.filter(acc => 
      !['1102', '1107', '1201', '1202', '2102', '4102', '4104', '4106', '4107', '5101'].includes(acc.code)
    );

    const clinicAccounts: Account[] = [
      {
        id: `${clinicId}_4130`,
        clinicId,
        code: '4130',
        name: 'إيرادات الكشوفات والزيارات الطبية المباشرة',
        nameEn: 'Direct Clinic Consultation Revenues',
        type: 'revenue',
        category: 'operating_revenues',
        parentId: `${clinicId}_41`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'جميع إيرادات الكشوفات والمتابعات الطبية والاستشارات المسددة بالخزينة المباشرة للعيادة',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5130`,
        clinicId,
        code: '5130',
        name: 'مصروفات إيجار مقر العيادة والخدمات والمرافق العامة',
        nameEn: 'Clinic Rent & Shared Premises Costs',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'قيمة إيجار مقر العيادة السنوي/الشهري، بالإضافة لفواتير الكهرباء، المياه والإنترنت المشتركة للعيادة',
        createdAt: timestamp
      },
      {
        id: `${clinicId}_5131`,
        clinicId,
        code: '5131',
        name: 'مصروفات صيانة وتحديث الأجهزة الطبية البسيطة',
        nameEn: 'Medical Equipment & Device Maintenance',
        type: 'expense',
        category: 'operating_expenses',
        parentId: `${clinicId}_51`,
        level: 3,
        openingBalance: 0,
        currentBalance: 0,
        isSystemAccount: true,
        description: 'تكاليف تعقيم الأجهزة، صيانة السونار البسيط، كراسي الفحص، وأجهزة قياس الضغط والسكر وحرارة الجسم',
        createdAt: timestamp
      }
    ];
    return [...filteredBase, ...clinicAccounts];
  }

  if (templateType === 'pharmacy') {
    // Specialized Pharmacy Chart of Accounts
    const pharmacyAccounts: Account[] = [
      // 1. Assets
      { id: `${clinicId}_p1`, clinicId, code: '1', name: 'الأصول (الصيدلية)', nameEn: 'Assets', type: 'asset', category: 'root', level: 1, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p11`, clinicId, code: '11', name: 'الأصول المتداولة (الصيدلية)', nameEn: 'Current Assets', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p1`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p1101`, clinicId, code: '1101', name: 'الخزينة الرئيسية للصيدلية', nameEn: 'Main Pharmacy Safe', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p11`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'المبالغ النقدية المودعة بالحفظ الرئيسي للصيدلية', createdAt: timestamp },
      { id: `${clinicId}_p1102`, clinicId, code: '1102', name: 'خزينة الكاونتر والشيفتات اليومية', nameEn: 'POS Counter Cash Drawers', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p11`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'النقدية بالدرج والمناوبات مع الصيادلة', createdAt: timestamp },
      { id: `${clinicId}_p1103`, clinicId, code: '1103', name: 'الحساب البنكي ونقاط البيع الإلكترونية (POS)', nameEn: 'Bank & POS Card Terminals', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p11`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p1106`, clinicId, code: '1106', name: 'مخزون الأدوية والمستحضرات المتاحة', nameEn: 'Medicine & Drug Inventory', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p11`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'قيمة بضاعة الأدوية والمستلزمات ومستحضرات التجميل المتاحة للبيع', createdAt: timestamp },
      { id: `${clinicId}_p11061`, clinicId, code: '11061', name: 'مخزون الأدوية والروشتات والمضادات الحيوية', nameEn: 'Prescription & Antibiotics Stock', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p1106`, level: 4, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p11062`, clinicId, code: '11062', name: 'مخزون مستحضرات التجميل والعناية بالبشرة', nameEn: 'Cosmetics & Personal Care Stock', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p1106`, level: 4, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p11063`, clinicId, code: '11063', name: 'مخزون حليب ومستلزمات ومكملات الأطفال', nameEn: 'Baby Milk & Formula Stock', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p1106`, level: 4, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p1107`, clinicId, code: '1107', name: 'عملاء ومستحقات المبيعات الآجلة للشركات والنقابات', nameEn: 'Pharmacy Receivables (Credit Sales)', type: 'asset', category: 'current_assets', parentId: `${clinicId}_p11`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      
      // 12. Fixed Assets
      { id: `${clinicId}_p12`, clinicId, code: '12', name: 'الأصول الثابتة للصيدلية', nameEn: 'Pharmacy Fixed Assets', type: 'asset', category: 'fixed_assets', parentId: `${clinicId}_p1`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p1201`, clinicId, code: '1201', name: 'ثلاجات حفظ الأنسولين والأجهزة الإلكترونية', nameEn: 'Medicine Refrigerators & Scanners', type: 'asset', category: 'fixed_assets', parentId: `${clinicId}_p12`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p1202`, clinicId, code: '1202', name: 'أرفف وديكورات وكاونترات الصيدلية', nameEn: 'Pharmacy Racks & Shelving', type: 'asset', category: 'fixed_assets', parentId: `${clinicId}_p12`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },

      // 2. Liabilities
      { id: `${clinicId}_p2`, clinicId, code: '2', name: 'الالتزامات (الصيدلية)', nameEn: 'Liabilities', type: 'liability', category: 'root', level: 1, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p21`, clinicId, code: '21', name: 'الالتزامات المتداولة (الموردين)', nameEn: 'Current Liabilities', type: 'liability', category: 'current_liabilities', parentId: `${clinicId}_p2`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p2101`, clinicId, code: '2101', name: 'حسابات شركات توزيع الأدوية والموردين', nameEn: 'Pharma Distributors & Suppliers A/P', type: 'liability', category: 'current_liabilities', parentId: `${clinicId}_p21`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'مستحقات مخازن وشركات توزيع الأدوية المعتمدة', createdAt: timestamp },
      { id: `${clinicId}_p2102`, clinicId, code: '2102', name: 'أمانات المراجعين والتأمين الصحي', nameEn: 'Co-pay & Insurance Deposits', type: 'liability', category: 'current_liabilities', parentId: `${clinicId}_p21`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },

      // 3. Equity
      { id: `${clinicId}_p3`, clinicId, code: '3', name: 'حقوق الملكية (الصيدلية)', nameEn: 'Equity', type: 'equity', category: 'root', level: 1, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p31`, clinicId, code: '31', name: 'رأس المال والأرباح', nameEn: 'Capital & Reserves', type: 'equity', category: 'equity', parentId: `${clinicId}_p3`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p3101`, clinicId, code: '3101', name: 'رأس مال الصيدلية المعتمد', nameEn: 'Pharmacy Capital', type: 'equity', category: 'equity', parentId: `${clinicId}_p31`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },

      // 4. Revenues
      { id: `${clinicId}_p4`, clinicId, code: '4', name: 'الإيرادات (الصيدلية)', nameEn: 'Revenues', type: 'revenue', category: 'root', level: 1, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p41`, clinicId, code: '41', name: 'إيرادات المبيعات والخدمات الدوائية', nameEn: 'Pharmacy Sales Revenues', type: 'revenue', category: 'operating_revenues', parentId: `${clinicId}_p4`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p4101`, clinicId, code: '4101', name: 'مبيعات الأدوية والروشتات المباشرة (نقدي)', nameEn: 'Cash Medicine & Prescription Sales', type: 'revenue', category: 'operating_revenues', parentId: `${clinicId}_p41`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p4102`, clinicId, code: '4102', name: 'مبيعات مستحضرات التجميل والعناية الشخصية', nameEn: 'Cosmetics & Skincare Sales', type: 'revenue', category: 'operating_revenues', parentId: `${clinicId}_p41`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p4103`, clinicId, code: '4103', name: 'مبيعات التعاقدات والروشتات النقابية والتأمين', nameEn: 'Insurance & Corporate Prescription Sales', type: 'revenue', category: 'operating_revenues', parentId: `${clinicId}_p41`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p4104`, clinicId, code: '4104', name: 'خصم مكتسب وحوافز الشراء من شركات الأدوية', nameEn: 'Earned Discounts & Vendor Rebates', type: 'revenue', category: 'operating_revenues', parentId: `${clinicId}_p41`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },

      // 5. Expenses
      { id: `${clinicId}_p5`, clinicId, code: '5', name: 'المصروفات والتكاليف (الصيدلية)', nameEn: 'Expenses & COGS', type: 'expense', category: 'root', level: 1, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p51`, clinicId, code: '51', name: 'تكلفة المبيعات والمصروفات التشغيلية للصيدلية', nameEn: 'COGS & Pharmacy Expenses', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p5`, level: 2, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p5101`, clinicId, code: '5101', name: 'تكلفة البضاعة المباعة (أدوية ومستلزمات COGS)', nameEn: 'Cost of Goods Sold (Drugs)', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'التكلفة الفعلية للأدوية المباعة للمرضى والمراجعين', createdAt: timestamp },
      { id: `${clinicId}_p5102`, clinicId, code: '5102', name: 'خسائر وتوالف الأدوية منتهية الصلاحية (Expired)', nameEn: 'Expired & Damaged Drugs Loss', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, description: 'قيمة الأدوية والمستحضرات التالفة أو التي انتهت صلاحيتها ولم تُرد للمورد', createdAt: timestamp },
      { id: `${clinicId}_p5103`, clinicId, code: '5103', name: 'رواتب وحوافز الصيادلة ومساعدي الكاونتر', nameEn: 'Pharmacists Salaries & Bonuses', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p5104`, clinicId, code: '5104', name: 'مصروفات إيجار وترخيص وتفتيش الصيدلية', nameEn: 'Pharmacy Rent & Inspection Fees', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p5105`, clinicId, code: '5105', name: 'كهرباء ومرافق وتبريد أجهزة الحفظ', nameEn: 'Electricity & Refrigeration Power Costs', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp },
      { id: `${clinicId}_p5106`, clinicId, code: '5106', name: 'عجز وتفاوت ورديات الخزينة والصيادلة', nameEn: 'Cash Shift Shortage Expense', type: 'expense', category: 'operating_expenses', parentId: `${clinicId}_p51`, level: 3, openingBalance: 0, currentBalance: 0, isSystemAccount: true, createdAt: timestamp }
    ];
    return pharmacyAccounts;
  }

  return baseAccounts;
}
